// Mocks generated by Mockito 5.4.6 from annotations
// in lumiai/test/features/settings/ui/settings_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:lumiai/core/services/feedback_service.dart' as _i4;
import 'package:lumiai/core/services/tts_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [TtsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTtsService extends _i1.Mock implements _i2.TtsService {
  MockTtsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i2.VoiceOption> get availableVoices =>
      (super.noSuchMethod(
            Invocation.getter(#availableVoices),
            returnValue: <_i2.VoiceOption>[],
          )
          as List<_i2.VoiceOption>);

  @override
  _i3.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> speak(String? text) =>
      (super.noSuchMethod(
            Invocation.method(#speak, [text]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> stop() =>
      (super.noSuchMethod(
            Invocation.method(#stop, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> setPitch(double? pitch) =>
      (super.noSuchMethod(
            Invocation.method(#setPitch, [pitch]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> setRate(double? rate) =>
      (super.noSuchMethod(
            Invocation.method(#setRate, [rate]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> setVoice(String? voiceIdentifier) =>
      (super.noSuchMethod(
            Invocation.method(#setVoice, [voiceIdentifier]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> setLanguage(String? language) =>
      (super.noSuchMethod(
            Invocation.method(#setLanguage, [language]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [FeedbackService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFeedbackService extends _i1.Mock implements _i4.FeedbackService {
  MockFeedbackService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> triggerSuccessFeedback() =>
      (super.noSuchMethod(
            Invocation.method(#triggerSuccessFeedback, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> triggerErrorFeedback() =>
      (super.noSuchMethod(
            Invocation.method(#triggerErrorFeedback, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  void triggerMediumFeedback() => super.noSuchMethod(
    Invocation.method(#triggerMediumFeedback, []),
    returnValueForMissingStub: null,
  );

  @override
  void triggerSelectionFeedback() => super.noSuchMethod(
    Invocation.method(#triggerSelectionFeedback, []),
    returnValueForMissingStub: null,
  );
}
